$ErrorActionPreference = 'Stop'

$root = Split-Path -Parent $PSScriptRoot
$utf8 = [System.Text.Encoding]::UTF8

function Read-Text($relative) {
    return [System.IO.File]::ReadAllText((Join-Path $root $relative), $utf8)
}

function Assert-True($condition, $message) {
    if (-not $condition) {
        throw "FAIL: $message"
    }
    Write-Host "OK: $message"
}

function Assert-Contains($relative, $needle, $message) {
    $text = Read-Text $relative
    Assert-True ($text.Contains($needle)) $message
}

function Assert-NotContains($relative, $needle, $message) {
    $text = Read-Text $relative
    Assert-True (-not $text.Contains($needle)) $message
}

Assert-True (Test-Path (Join-Path $root 'assets/vendor/pov-calendar/pov-calendar.js')) 'local calendar module exists'
Assert-True ((Get-Item (Join-Path $root 'assets/brand/pro-ocean-logo-blue.svg')).Length -gt 50000) 'supplied logo SVG is installed'
Assert-True ((Get-Item (Join-Path $root 'assets/brand/pro-ocean-symbol-blue.svg')).Length -gt 50000) 'supplied symbol SVG is installed'
Assert-True (Test-Path (Join-Path $root 'src/Portal/OperationsPortal.php')) 'hybrid operations portal controller exists'
Assert-True (Test-Path (Join-Path $root 'src/Security/Capabilities.php')) 'operations capability matrix exists'
Assert-True (Test-Path (Join-Path $root 'templates/operations-portal.php')) 'standalone operations portal template exists'
Assert-True (Test-Path (Join-Path $root 'assets/dist/portal.css')) 'standalone operations portal styles exist'

Assert-Contains 'src/Portal/OperationsPortal.php' "public const SLUG = 'van-operations'" 'operations portal uses the stable /van-operations path'
Assert-Contains 'src/Portal/OperationsPortal.php' 'is_user_logged_in()' 'operations portal requires a personal WordPress login'
Assert-Contains 'src/Portal/OperationsPortal.php' 'auth_redirect();' 'unauthenticated portal visitors are sent to WordPress login'
Assert-Contains 'src/Portal/OperationsPortal.php' 'current_user_can(Capabilities::ACCESS_PORTAL)' 'operations portal checks its access capability server-side'
Assert-Contains 'src/Portal/OperationsPortal.php' 'nocache_headers();' 'protected portal responses disable HTTP caching'
Assert-Contains 'src/Portal/OperationsPortal.php' "define('DONOTCACHEPAGE', true)" 'protected portal opts out of page caches'
Assert-Contains 'src/Portal/OperationsPortal.php' 'X-Robots-Tag: noindex, nofollow, noarchive, nosnippet' 'protected portal sends a noindex header'
Assert-Contains 'src/Portal/OperationsPortal.php' "get_post_meta(`$pageId, '_pov_operations_portal', true) === '1'" 'portal reuses only a page it owns'
Assert-NotContains 'src/Portal/OperationsPortal.php' 'get_page_by_path(self::SLUG' 'portal never adopts an unrelated page with the same slug'
Assert-Contains 'src/Portal/OperationsPortal.php' 'self::firstAllowedPage() === null' 'portal denies incomplete access assignments without a redirect loop'
Assert-Contains 'src/Portal/OperationsPortal.php' "add_filter('get_pages_query_args'" 'portal is excluded from dynamic public page-list blocks'
Assert-Contains 'src/Portal/OperationsPortal.php' "add_filter('render_block_core/navigation-link'" 'portal is excluded from explicit public block navigation'
Assert-Contains 'assets/dist/portal.css' 'box-sizing: border-box; width: 100%' 'portal shell padding cannot create horizontal page overflow'
Assert-Contains 'src/Admin/Menu.php' "get_option('pov_demo_mode', '0') === '1'" 'deterministic demo routing does not show a false provider warning'
Assert-Contains 'templates/operations-portal.php' 'noindex,nofollow,noarchive,nosnippet' 'protected portal template includes a robots fallback'
Assert-NotContains 'src/Portal/OperationsPortal.php' 'post_password' 'operations portal does not use a shared page password'
Assert-Contains 'src/Plugin.php' '(new OperationsPortal())->register();' 'plugin registers the hybrid operations portal'
Assert-Contains 'src/Activation.php' 'Capabilities::syncRoles();' 'activation installs the operations roles'
Assert-Contains 'src/Activation.php' 'OperationsPortal::ensurePage();' 'activation creates the operations portal page'

$capabilitiesText = Read-Text 'src/Security/Capabilities.php'
$teamMatch = [regex]::Match($capabilitiesText, '\$teamCaps\s*=\s*array_fill_keys\(\[(?<caps>.*?)\],\s*true\);', [System.Text.RegularExpressions.RegexOptions]::Singleline)
$readerMatch = [regex]::Match($capabilitiesText, '\$readerCaps\s*=\s*array_fill_keys\(\[(?<caps>.*?)\],\s*true\);', [System.Text.RegularExpressions.RegexOptions]::Singleline)
Assert-True $teamMatch.Success 'team role capability block is explicit'
Assert-True $readerMatch.Success 'read-only role capability block is explicit'
$teamCapabilities = $teamMatch.Groups['caps'].Value
$readerCapabilities = $readerMatch.Groups['caps'].Value
Assert-Contains 'src/Security/Capabilities.php' "public const TEAM_ROLE = 'pov_van_team'" 'team role has a stable role key'
Assert-Contains 'src/Security/Capabilities.php' "public const READER_ROLE = 'pov_van_reader'" 'read-only role has a stable role key'
foreach ($capability in @('ACCESS_PORTAL', 'VIEW_REQUESTS', 'MANAGE_REQUESTS', 'SEND_RESPONSES', 'VIEW_TOURS', 'MANAGE_TOURS', 'VIEW_CALENDAR', 'MANAGE_CALENDAR', 'VIEW_STATISTICS', 'EXPORT_CALENDAR')) {
    Assert-True ($teamCapabilities.Contains("self::$capability")) "team role receives $capability"
}
foreach ($capability in @('ACCESS_PORTAL', 'VIEW_TOURS', 'VIEW_CALENDAR', 'VIEW_STATISTICS')) {
    Assert-True ($readerCapabilities.Contains("self::$capability")) "read-only role receives $capability"
}
foreach ($capability in @('VIEW_REQUESTS', 'MANAGE_REQUESTS', 'SEND_RESPONSES', 'MANAGE_TOURS', 'MANAGE_CALENDAR', 'EXPORT_CALENDAR', 'MANAGE_PRIVACY')) {
    Assert-True (-not $readerCapabilities.Contains("self::$capability")) "read-only role does not receive $capability"
}

$menuText = Read-Text 'src/Admin/Menu.php'
$adminMenuMatch = [regex]::Match($menuText, 'public function menus\(\): void\s*\{(?<body>.*?)\n\s*\}\s*\n\s*public function assets', [System.Text.RegularExpressions.RegexOptions]::Singleline)
Assert-True $adminMenuMatch.Success 'WordPress admin menu registration can be audited'
$adminMenuBody = $adminMenuMatch.Groups['body'].Value
Assert-True ($adminMenuBody.Contains("'pov-settings'")) 'WordPress admin keeps technical settings'
foreach ($operationalPage in @('pov-requests', 'pov-routes', 'pov-statistics', 'pov-calendar')) {
    Assert-True (-not $adminMenuBody.Contains("'$operationalPage'")) "WordPress admin does not register $operationalPage"
}
Assert-Contains 'src/Admin/Menu.php' 'current_user_can(Capabilities::EXPORT_CALENDAR)' 'calendar export is rendered only with its capability'
Assert-Contains 'src/Admin/Menu.php' 'current_user_can(Capabilities::MANAGE_CALENDAR)' 'calendar mutation fields are rendered only with their capability'
Assert-Contains 'src/Admin/Menu.php' 'current_user_can(Capabilities::SEND_RESPONSES)' 'response mutations are rendered only with their capability'
Assert-Contains 'src/Admin/Menu.php' 'current_user_can(Capabilities::MANAGE_REQUESTS)' 'request mutations are rendered only with their capability'
Assert-Contains 'src/Admin/Menu.php' '$this->guard(''pov_save_calendar_day'', Capabilities::MANAGE_CALENDAR)' 'calendar writes use a granular server-side guard'
Assert-Contains 'src/Admin/Menu.php' '$this->guard(''pov_recalculate_suggestions'', Capabilities::MANAGE_TOURS)' 'tour recalculation uses a granular server-side guard'
Assert-Contains 'src/Admin/Menu.php' '$this->guard(''pov_send_response'', Capabilities::SEND_RESPONSES)' 'outgoing responses use a granular server-side guard'
Assert-Contains 'src/Admin/Menu.php' '$this->guard(''pov_save_request_address'', Capabilities::MANAGE_REQUESTS)' 'address changes use a granular server-side guard'
Assert-Contains 'src/Admin/Menu.php' '$this->guard(''pov_download_ics'', Capabilities::EXPORT_CALENDAR)' 'calendar downloads use a granular server-side guard'
Assert-Contains 'src/Rest/AdminController.php' "current_user_can(`$capability)" 'operations REST routes enforce their declared capability'
Assert-Contains 'src/Service/MailService.php' "OperationsPortal::url('pov-requests'" 'team notification links open the protected portal'
Assert-NotContains 'src/Service/MailService.php' 'admin.php?page=pov-requests' 'team notification no longer links into wp-admin'

Assert-Contains 'assets/dist/frontend.js' 'new window.POVCalendar' 'frontend uses bundled calendar module'
Assert-Contains 'assets/dist/frontend.js' 'async function checkRoute' 'frontend checks route suggestions on demand'
Assert-Contains 'assets/dist/frontend.js' 'requestTimeoutMs' 'frontend stops an unresponsive route request'
Assert-Contains 'assets/dist/frontend.js' ').slice(0, 2)' 'frontend shows exactly two route dates'
Assert-Contains 'assets/dist/frontend.js' 'firstSuggestedDate.getDate() + 14' 'frontend hides recommendations with less than two weeks lead time'
Assert-Contains 'assets/dist/frontend.js' "Intl.DateTimeFormat('de-DE'" 'frontend formats visible dates in German'
Assert-Contains 'assets/dist/frontend.js' 'copyRouteRegionToForm' 'editable booking details reuse postal code and state'
Assert-NotContains 'assets/dist/frontend.js' 'reason_summary' 'frontend omits route comments'
Assert-Contains 'templates/frontend-booking.php' 'Hol das Meer zu dir' 'frontend uses the finalized sea headline'
Assert-NotContains 'templates/frontend-booking.php' 'data-action="toggle-calendar"' 'frontend calendar stays open without a visibility toggle'
Assert-Contains 'templates/frontend-booking.php' 'id="pov-calendar-panel"' 'frontend calendar is rendered immediately'
Assert-NotContains 'templates/frontend-booking.php' 'id="pov-range-panel"' 'calendar replaces the redundant date-range panel'
Assert-NotContains 'templates/frontend-booking.php' 'data-action="toggle-range"' 'frontend no longer hides the date-range alternative behind a toggle'
Assert-Contains 'templates/frontend-booking.php' 'name="postal_code"' 'postal code stays editable in the form'
Assert-Contains 'templates/frontend-booking.php' 'name="state_code"' 'state stays editable in the form'
Assert-Contains 'templates/frontend-booking.php' 'Schule (kostenlos)' 'school bookings communicate their free offer'
Assert-Contains 'templates/frontend-booking.php' 'Veranstaltung (ggf. kostenpflichtig)' 'event bookings communicate possible costs'
Assert-Contains 'templates/frontend-booking.php' 'data-event-section="Schule"' 'frontend reveals school-specific planning questions'
Assert-Contains 'templates/frontend-booking.php' 'data-event-section="Veranstaltung"' 'frontend reveals event-specific planning questions'
Assert-Contains 'templates/frontend-booking.php' 'data-event-section="Sonstiges"' 'frontend reveals other-event planning questions'
Assert-Contains 'assets/dist/frontend.js' 'updateEventTypeSections' 'event-type sections are controlled dynamically'
Assert-Contains 'templates/frontend-booking.php' 'name="contact_role"' 'frontend captures the requester role'
Assert-Contains 'templates/frontend-booking.php' 'name="institution_website"' 'frontend captures the institution website'
Assert-Contains 'templates/frontend-booking.php' 'name="availability_window"' 'frontend captures the planning time window with the detail questions'
Assert-Contains 'templates/frontend-booking.php' 'name="school_schedule_notes"' 'school bookings capture planning wishes'
Assert-Contains 'templates/frontend-booking.php' 'mindestens 1 Stunde' 'frontend explains required setup access'
Assert-NotContains 'templates/frontend-booking.php' 'value="unknown"' 'public onsite questions offer clear yes-or-no choices'
Assert-Contains 'templates/frontend-booking.php' 'Schulhof' 'van parking offers a schoolyard option'
Assert-Contains 'templates/frontend-booking.php' 'select name="parking_type" required' 'van parking type is a required selection'
Assert-Contains 'templates/frontend-booking.php' 'Länge: 6 m, Breite: 2,05 m, Höhe: 2,522 m' 'frontend communicates the van dimensions'
Assert-Contains 'templates/frontend-booking.php' 'Google-Maps-Link zum Stellplatz' 'frontend captures the exact van parking location as a Maps link'
Assert-Contains 'templates/frontend-booking.php' 'name="electricity_outdoor_distance_m"' 'outdoor power is captured as a measurable distance'
Assert-Contains 'templates/frontend-booking.php' 'name="electricity_outdoor_location"' 'outdoor power captures the connection location'
Assert-Contains 'templates/frontend-booking.php' 'Benötigte Kabellänge (Meter)' 'outdoor power asks for the required cable length'
Assert-NotContains 'templates/frontend-booking.php' 'name="electricity_outdoor_available"' 'outdoor power is not an unclear yes-or-no question'
Assert-Contains 'assets/dist/frontend.css' '.pov-question input[type="radio"]' 'choice styling hides only radio inputs'
Assert-NotContains 'assets/dist/frontend.css' '.pov-question input {' 'ordinary fields inside onsite cards remain visible'
Assert-NotContains 'assets/dist/frontend.js' 'form.elements.school_adult_count.min' 'one adult remains valid regardless of class count'
Assert-NotContains 'src/Rest/RequestController.php' '$adults < $classCount * $teachersPerClass' 'server accepts one adult without multiplying teachers per class'
Assert-Contains 'src/Database/Schema.php' 'electricity_outdoor_location VARCHAR(500)' 'request schema stores the outdoor power location'
Assert-Contains 'templates/frontend-booking.php' 'data-role="walk-in-dialog"' 'frontend provides walk-in event details'
Assert-Contains 'assets/dist/frontend.js' 'eligible_dates' 'frontend consumes geo-eligible calendar dates'
Assert-Contains 'assets/dist/frontend.js' 'geo_unavailable' 'frontend greys globally available dates outside the geo criteria'
Assert-Contains 'assets/dist/frontend.css' '--pov-mint: #E4F3EA' 'geo-eligible calendar days use the green Pro Ocean palette'
Assert-Contains 'assets/dist/frontend.js' "rangeOnly ? 'Bitte Zeitraum anfragen.'" 'empty geo eligibility offers only a date-range request'
Assert-Contains 'assets/vendor/pov-calendar/pov-calendar.js' 'dataset.weekend' 'calendar exposes weekend days for styling and semantics'
Assert-Contains 'assets/vendor/pov-calendar/pov-calendar.js' 'dataset.date = date' 'calendar exposes exact dates for reliable interaction'
Assert-Contains 'assets/vendor/pov-calendar/pov-calendar.js' "Intl.DateTimeFormat('de-DE'" 'calendar formats dates in German'
Assert-NotContains 'templates/frontend-booking.php' '<i class="is-available"></i>' 'legend omits self-explanatory green dates'
Assert-NotContains 'templates/frontend-booking.php' '<i class="is-limited"></i>' 'legend omits self-explanatory yellow dates'
Assert-Contains 'templates/frontend-booking.php' 'name="school_lesson_duration"' 'school bookings capture the lesson duration'
Assert-Contains 'templates/frontend-booking.php' 'value="hdmi"' 'frontend captures HDMI availability'
Assert-Contains 'templates/frontend-booking.php' 'data-natural-water-location' 'frontend captures an optional Maps link for nearby water'
Assert-Contains 'assets/vendor/pov-calendar/pov-calendar.js' 'row.is_requestable' 'request-only calendar days can start a date request'
Assert-Contains 'templates/frontend-booking.php' 'ffentliches Event' 'frontend labels public events consistently'
Assert-NotContains 'templates/frontend-booking.php' '<i class="is-limited"></i>Auf Anfrage' 'frontend legend leaves requestable color states out'
Assert-Contains 'templates/frontend-booking.php' 'Nicht buchbar' 'frontend legend uses clear unavailable wording'
Assert-NotContains 'templates/frontend-booking.php' 'Eingeschränkt' 'frontend no longer uses unclear limited wording'
Assert-NotContains 'src/Admin/Menu.php' 'mapPanel' 'admin contains no map panels'
Assert-NotContains 'assets/dist/admin.js' 'POVLeaflet' 'admin JavaScript contains no map renderer'
Assert-NotContains 'src/Admin/Menu.php' 'pov-dashboard' 'admin starts directly in the request inbox'
Assert-Contains 'src/Admin/Menu.php' 'pov_send_response' 'admin provides one response workflow'
Assert-Contains 'src/Admin/Menu.php' 'pov_create_manual_appointment' 'admin calendar can create internal appointments directly'
Assert-Contains 'src/Admin/Menu.php' 'calendar_day_id=' 'public events are included in calendar exports'
Assert-Contains 'src/Admin/Menu.php' 'Info Lehrkräfte' 'communication workflow includes teacher information'
Assert-Contains 'src/Admin/Menu.php' 'pov_log_communication' 'admin can record incoming and offline communication'
Assert-Contains 'src/Admin/Menu.php' 'pov_save_request_details' 'admin can update request and appointment details'
Assert-Contains 'src/Repository/ClassRepository.php' 'syncParticipantTotal' 'edited participant totals stay consistent with class data'
Assert-NotContains 'src/Activation.php' 'SET children_count = participant_total' 'legacy participant splits are not invented'
Assert-Contains 'src/Admin/Menu.php' 'reactivate_appointment' 'cancelled appointments require explicit reactivation'
Assert-Contains 'src/Admin/Menu.php' 'pov_save_appointment_outcome' 'admin can record reached participants'
Assert-Contains 'src/Admin/Menu.php' '$appointmentRepository->find($appointmentId)' 'outcome audit entries derive their request from the appointment'
Assert-Contains 'src/Admin/Menu.php' 'pov_save_tour_expense' 'tour planning can record overnight and other costs'
Assert-Contains 'src/Admin/Menu.php' 'https://www.google.com/maps/search/' 'complete weekly tours open as Google Maps POIs'
Assert-Contains 'src/Admin/Menu.php' 'Tourstopps als POIs in Google Maps' 'tour planning offers one consolidated Google Maps POI action'
Assert-Contains 'src/Admin/Menu.php' "'accept' => 'Zusage'" 'admin exposes acceptance'
Assert-Contains 'src/Admin/Menu.php' "'question' =>" 'admin exposes questions'
Assert-Contains 'src/Admin/Menu.php' "'reject' => 'Absage'" 'admin exposes rejection'
Assert-Contains 'src/Admin/Menu.php' 'pov_team_notification_emails' 'team notification addresses are configurable'
Assert-Contains 'src/Admin/Menu.php' 'pov-statistics' 'admin exposes route and cost statistics'
Assert-Contains 'src/Service/StatisticsService.php' 'personnel_cost' 'statistics include personnel costs'
Assert-Contains 'src/Admin/Menu.php' 'pov_personnel_hourly_rate' 'personnel rates are editable'
Assert-Contains 'src/Service/RouteOptimizationService.php' 'route_duration_minutes' 'route planning exposes estimated driving time'
Assert-Contains 'src/Service/WeeklyClusterService.php' 'overnightRecommendations' 'weekly tours recommend overnight regions'
Assert-Contains 'src/Admin/Menu.php' 'pov-tour-timeline' 'weekly tours render as an ordered timeline'
Assert-Contains 'src/Admin/Menu.php' 'pov_response_accept_template' 'request responses use editable templates'
Assert-Contains 'src/Service/MailService.php' 'AttachmentService())->paths($attachmentIds)' 'outgoing mail supports attachments'
Assert-Contains 'src/Service/AttachmentService.php' 'pov-private-attachments' 'communication attachments are stored outside the public document root'
Assert-Contains 'src/Admin/Menu.php' 'pov_download_attachment' 'communication attachments use an authenticated download action'
Assert-Contains 'src/Service/AttachmentService.php' 'hasErrors' 'attachment upload errors remain visible to the team'
Assert-Contains 'src/Service/AttachmentService.php' 'rollback' 'partial attachment uploads are rolled back'
Assert-Contains 'src/Service/AttachmentService.php' "'post_status' => 'private'" 'communication attachment metadata is private'
Assert-Contains 'src/Service/AttachmentService.php' '_pov_private_attachment' 'private attachments are excluded from public REST media'
Assert-Contains 'uninstall.php' 'wp_delete_attachment' 'uninstall cleanup removes communication attachments'
Assert-Contains 'uninstall.php' '_pov_private_attachment' 'uninstall cleanup also removes orphaned private attachment records'
Assert-Contains 'src/Service/AttachmentService.php' 'deleteUnusedAttachments' 'removed standard attachments are deleted when no longer referenced'
Assert-Contains 'src/Service/MailService.php' "'pov_' . `$type . '_attachment_ids'" 'response templates support standard attachments'
Assert-Contains 'src/Repository/CommunicationRepository.php' 'pov_communications' 'communication hub stores request correspondence'
Assert-Contains 'src/Repository/TourExpenseRepository.php' 'pov_tour_expenses' 'tour expenses are persisted'
Assert-Contains 'assets/dist/admin.js' 'automaticMessage' 'response templates switch with the response type'
Assert-Contains 'src/Admin/Menu.php' 'pov_test_geo' 'geo providers can be tested from settings'
Assert-Contains 'src/Admin/Menu.php' 'Geocoding und Fahrzeitmatrix' 'geo test covers address and routing analysis'
Assert-Contains 'src/Admin/Menu.php' 'pov_save_request_address' 'request addresses can be corrected in the backend'
Assert-Contains 'src/Admin/Menu.php' 'pov_retry_missing_addresses' 'missing addresses can be checked again in one action'
Assert-Contains 'src/Repository/AppointmentRepository.php' 'syncAddressFromRequest' 'corrected addresses propagate to confirmed appointments'
Assert-Contains 'assets/dist/admin.js' 'bindProviderSettings' 'routing settings hide fields that do not belong to the selected provider'
Assert-Contains 'src/Routing/PeliasGeocodingProvider.php' "'country' => 'Germany'" 'HeiGIT structured geocoding uses the accepted country value'
Assert-Contains 'src/Routing/PeliasGeocodingProvider.php' "wp_get_environment_type() === 'local'" 'local SSL workaround stays limited to the local environment'
Assert-Contains 'src/Admin/Menu.php' 'calendar_date_from' 'admin calendar supports start date'
Assert-Contains 'src/Admin/Menu.php' 'calendar_date_to' 'admin calendar supports end date'
Assert-Contains 'src/Admin/Menu.php' 'custom_start_postal_code' 'admin calendar supports start point postal code'
Assert-Contains 'src/Admin/Menu.php' 'resolveCalendarStartPoint' 'admin calendar resolves start point'
Assert-Contains 'src/Admin/Menu.php' 'ProviderFactory())->geocoding()' 'admin calendar uses configured geocoding provider'
Assert-Contains 'src/Admin/Menu.php' 'adminCalendarGrid' 'admin calendar renders a real month grid'
Assert-Contains 'src/Admin/Menu.php' 'adminCalendarEvents' 'admin calendar aggregates operational events'
Assert-Contains 'src/Admin/Menu.php' 'dateAllowedForRequest' 'appointment confirmation is constrained to request dates'
Assert-Contains 'src/Admin/Menu.php' 'min="' 'appointment confirmation date has min constraint'
Assert-Contains 'src/Admin/Menu.php' 'max="' 'appointment confirmation date has max constraint'
Assert-Contains 'assets/dist/admin.js' 'syncDateRange' 'admin date pickers are dependency-sensitive'
Assert-Contains 'assets/dist/admin.js' 'end.min = start.value' 'end date cannot be before start date'
Assert-Contains 'src/Repository/CalendarDayRepository.php' 'upsertRange' 'calendar repository saves date ranges'
Assert-Contains 'src/Service/AvailabilityService.php' "format('N') >= 6" 'public calendar marks weekends separately'
Assert-Contains 'src/Service/AvailabilityService.php' 'is_weekend' 'public calendar exposes weekend metadata'
Assert-Contains 'src/Service/AvailabilityService.php' "'public_state' => 'past'" 'past calendar days have a dedicated state'
Assert-Contains 'assets/dist/frontend.css' '.pov-day[data-state="past"]' 'past calendar days are styled in grey'
Assert-Contains 'src/Service/AvailabilityService.php' 'Auf Anfrage' 'public calendar labels limited days as request-only'
Assert-Contains 'src/Service/AvailabilityService.php' 'CalendarState::WALK_IN' 'public availability exposes walk-in events'
Assert-Contains 'src/Service/PublicRecommendationService.php' "format('N') >= 6" 'public recommendations skip weekends'
Assert-Contains 'src/Service/PublicRecommendationService.php' 'compareDatedInsertion' 'public recommendations preserve dated tour order'
Assert-Contains 'src/Service/PublicRecommendationService.php' 'MIN_RECOMMENDATION_LEAD_DAYS = 14' 'public recommendations start at least two weeks ahead'
Assert-Contains 'src/Service/PublicRecommendationService.php' 'PostalCodeService' 'postal codes are resolved to a locality before geocoding'
Assert-Contains 'src/Service/PublicRecommendationService.php' "'direct'" 'weeks without tour stops reuse one direct-route calculation'
Assert-Contains 'src/Service/PublicRecommendationService.php' 'array_slice($suggestions, 0, 2)' 'recommendation API returns two best route dates'
Assert-Contains 'src/Service/PublicRecommendationService.php' "'eligible_dates'" 'recommendation API returns all geo-eligible calendar dates'
Assert-Contains 'src/Service/PublicRecommendationService.php' "'eligibility_token'" 'recommendation API signs geo-eligible dates'
Assert-Contains 'src/Rest/RequestController.php' 'EligibilityTokenService' 'specific bookings revalidate geo eligibility server-side'
Assert-Contains 'src/Service/PublicRecommendationService.php' 'GermanDateFormatter::dayMonth' 'flexible week labels use deterministic German month names'
Assert-Contains 'src/Service/PublicRecommendationService.php' 'weekSuggestions' 'public recommendations group good days into weeks'
Assert-Contains 'src/Service/PublicRecommendationService.php' "'suggestions' => `$publicSuggestions" 'public recommendation response uses a minimal date DTO'
Assert-NotContains 'src/Service/PublicRecommendationService.php' "'route_context'" 'public recommendation response omits geocoding coordinates'
Assert-Contains 'src/Service/PublicRecommendationService.php' 'PlanningSignalService' 'public recommendations combine routing with weekly and regional demand'
Assert-Contains 'src/Service/PlanningSignalService.php' 'WEEK_FILLING' 'planning signals prioritize filling active weeks'
Assert-Contains 'src/Service/PlanningSignalService.php' 'SAME_STATE_CLUSTER' 'planning signals aggregate requests by federal state'
Assert-Contains 'src/Service/PlanningSignalService.php' 'STATE_BLOCK_CONFLICT' 'multi-state planning avoids mixing unrelated regional blocks'
Assert-Contains 'src/Repository/RequestRepository.php' 'planned_suggestion_date' 'existing suggestions anchor flexible demand to one preferred week'
Assert-NotContains 'assets/dist/frontend.js' 'pov-suggestion-metrics' 'public suggestions omit distance and savings metrics'
Assert-Contains 'src/Service/RequestRoutingService.php' '_server_latitude' 'requests persist only server-side geocoding results'
Assert-Contains 'src/Service/RouteOptimizationService.php' 'calculateMatrix' 'route optimization uses the routing matrix'
Assert-Contains 'src/Service/RouteOptimizationService.php' 'compareInsertion' 'route optimization calculates incremental insertion costs'
Assert-Contains 'src/Service/RouteOptimizationService.php' 'return_route' 'dated suggestions extend the final return leg'
Assert-Contains 'src/Service/RouteOptimizationService.php' 'nearestNeighbour' 'weekly routes start from a deterministic nearest-neighbour plan'
Assert-Contains 'src/Service/RouteOptimizationService.php' 'improveOrder' 'weekly routes are locally improved after the initial plan'
Assert-Contains 'src/Service/RouteOptimizationService.php' 'optimizeWithFixedOrder' 'confirmed dates keep their sequence while flexible stops are inserted'
Assert-Contains 'src/Service/RouteOptimizationService.php' 'routeLegs' 'route planning exposes distances between appointments'
Assert-Contains 'src/Service/InternalSuggestionService.php' 'incremental_cost' 'internal suggestions rank real incremental route cost'
Assert-Contains 'src/Service/InternalSuggestionService.php' 'PlanningSignalService' 'internal suggestions also fill weeks and regional clusters'
Assert-Contains 'src/Service/WeeklyClusterService.php' 'cost_saved' 'weekly planning exposes estimated cost savings'
Assert-Contains 'src/Service/WeeklyClusterService.php' 'separateRequestStates' 'tour planning keeps multi-state requests in regional blocks'
Assert-Contains 'src/Service/WeeklyClusterService.php' 'state_codes' 'tour headers expose their federal-state grouping'
Assert-Contains 'src/Service/WeeklyClusterService.php' '$confirmedRequestIds' 'confirmed requests cannot appear twice in weekly tours'
Assert-Contains 'src/Repository/AppointmentRepository.php' 'GET_LOCK' 'appointment writes serialize access to an active date'
Assert-Contains 'src/Repository/AppointmentRepository.php' 'pov_request_appointment_' 'appointment writes also serialize access to a request'
Assert-Contains 'src/Repository/AppointmentRepository.php' 'withPlanningLocks' 'request changes keep planning locks through commit'
Assert-Contains 'src/Repository/AppointmentRepository.php' 'add_option($option' 'SQLite planning uses an atomic fallback lock'
Assert-Contains 'src/Repository/AppointmentRepository.php' 'option_value = %s' 'expired SQLite locks are removed with a compare-and-delete'
Assert-Contains 'src/Repository/AppointmentRepository.php' '$outcomeRecorded' 'request event types sync without overwriting recorded outcomes'
Assert-Contains 'src/Admin/Menu.php' 'Zusage erneut senden' 'failed acceptance mail can be sent again'
Assert-Contains 'src/Admin/Menu.php' '$acceptanceRetry && $activeAppointment' 'acceptance retries keep the confirmed appointment date'
Assert-Contains 'src/Admin/Menu.php' 'tourExpensesPanel($expenseRepository->all())' 'all overnight costs remain manageable after schedule changes'
Assert-Contains 'src/Repository/RequestRepository.php' "SET e.place = '', e.note = ''" 'anonymization removes free text from tour expenses'
Assert-Contains 'src/Service/StatisticsService.php' "'participants_children'" 'statistics aggregate reached children'
Assert-Contains 'src/Service/StatisticsService.php' "'participants_adults'" 'statistics aggregate reached adults'
Assert-Contains 'src/Service/StatisticsService.php' "'event_types'" 'statistics aggregate event types'
Assert-Contains 'src/Service/StatisticsService.php' "'overnight_cost'" 'statistics include overnight costs'
Assert-NotContains 'src/Admin/Menu.php' 'Übernachtungskosten hinzufügen' 'tour planning has no redundant free overnight-cost form'
Assert-Contains 'src/Admin/Menu.php' 'pov-stat-periods' 'statistics use readable period cards instead of one wide cost table'
Assert-Contains 'assets/dist/admin.css' '.pov-stat-costs' 'statistic cost groups have dedicated responsive styling'
Assert-Contains 'src/Service/StatisticsService.php' 'CalendarDayRepository())->walkIns()' 'standalone walk-in events feed the statistics'
Assert-Contains 'src/Service/WeeklyClusterService.php' 'confirmedClusters' 'confirmed statistics reuse weekly regional tour planning'
Assert-Contains 'src/Service/StatisticsService.php' 'confirmedClusters($appointments)' 'statistics request confirmed-only optimized tours'
Assert-Contains 'src/Service/StatisticsService.php' "'route_duration_minutes'" 'statistics use optimized tour driving time'
Assert-Contains 'src/Service/StatisticsService.php' '$visitHours * $hourlyRate * $personnelCount' 'visit personnel time remains charged per appointment'
Assert-Contains 'src/Service/WeeklyClusterService.php' 'pov_statistics_route_snapshot_' 'confirmed route metrics use persistent historical snapshots'
Assert-Contains 'src/Service/WeeklyClusterService.php' 'ordered_stop_keys' 'route snapshots retain ordering without storing full appointment records'
Assert-Contains 'src/Service/StatisticsService.php' 'tourPeriodAllocations' 'route legs are allocated to their stop periods'
Assert-Contains 'src/Service/StatisticsService.php' '$routeDuration * $durationWeight' 'travel time is distributed by routed leg duration'
Assert-Contains 'src/Service/StatisticsService.php' '$routeCost * $distanceWeight' 'route cost is distributed without duplication'
Assert-Contains 'src/Service/StatisticsService.php' 'walkInGroups' 'contiguous multi-day walk-ins count as one public event'
Assert-Contains 'src/Database/Schema.php' 'public_event_group VARCHAR(64)' 'walk-in ranges have a stable event identity'
Assert-Contains 'src/Service/StatisticsService.php' "'group:' . `$eventGroup" 'walk-in statistics prefer stable event identities'
Assert-Contains 'src/Service/StatisticsService.php' '$appointmentDates[$dateValue] ?? null' 'walk-in events remain visible on confirmed appointment days'
Assert-True (Test-Path (Join-Path $root 'tests/run-confirmed-tour-statistics.php')) 'executable confirmed-tour statistics regression test exists'
Assert-Contains 'src/Repository/CalendarDayRepository.php' "unset(`$eventForDay['participants_children']" 'multi-day walk-in attendance is counted once'
Assert-Contains 'src/Service/DemoDataService.php' 'POV_DEMO_DATA:' 'demo seed uses stable request markers'
Assert-Contains 'src/Service/DemoDataService.php' '_server_latitude' 'demo seed injects known server-side coordinates'
Assert-NotContains 'src/Service/DemoDataService.php' 'RequestRoutingService' 'demo seed never invokes external geocoding'
Assert-Contains 'tests/seed-local-demo-data.php' "in_array('--seed'" 'demo seed requires an explicit CLI flag'
Assert-Contains 'tests/seed-local-demo-data.php' "str_ends_with(`$homeHost, '.local')" 'demo seed is restricted to local WordPress hosts'
Assert-Contains 'playground/blueprint.template.json' '"resource": "url"' 'Playground demo installs the compact release archive'
Assert-Contains 'playground/blueprint.template.json' "update_option('pov_geocoding_provider', 'demo')" 'Playground geocoding is deterministic and network independent'
Assert-Contains 'playground/blueprint.template.json' "update_option('pov_routing_provider', 'null')" 'Playground routing uses the instant geographic fallback'
Assert-Contains 'playground/index.html' 'delete configured.login' 'public booking skips the slow administrator login step'
Assert-Contains 'playground/index.html' '?mode=seamless' 'public demo hides the Playground developer chrome'
Assert-Contains 'playground/blueprint.template.json' 'DemoDataService' 'Playground demo creates safe example records'
Assert-Contains 'playground/blueprint.template.json' 'pre_wp_mail' 'Playground demo disables outgoing mail'
Assert-Contains 'playground/blueprint.template.json' "update_option('permalink_structure', '/%postname%/')" 'Playground configures the portal landing path explicitly'
Assert-Contains 'playground/blueprint.template.json' 'flush_rewrite_rules();' 'Playground activates its portal rewrite rules'
Assert-Contains 'playground/index.html' 'https://playground.wordpress.net/' 'public launcher opens WordPress Playground'
Assert-Contains '.github/workflows/pages.yml' 'actions/deploy-pages@v4' 'GitHub Pages deployment is automated'
Assert-Contains '.github/workflows/pages.yml' 'PLUGIN_ARCHIVE="pro-ocean-van-${GITHUB_SHA}.zip"' 'GitHub Pages builds a commit-specific plugin archive'
Assert-Contains 'playground/blueprint.template.json' '__POV_PLUGIN_URL__' 'Pages injects the current plugin archive into the Playground blueprint'
Assert-NotContains 'playground/blueprint.template.json' 'releases/latest/download' 'Playground no longer loads a stale latest release'
Assert-Contains 'playground/index.html' "cache: 'no-store'" 'public demo bypasses stale blueprint browser caches'
Assert-Contains '.github/workflows/release.yml' 'gh release create' 'version tags publish the installable plugin archive'
Assert-Contains 'src/Database/Schema.php' 'sort_order INT UNSIGNED' 'suggestion ordering avoids the reserved SQL rank keyword'
Assert-NotContains 'src/Database/Schema.php' 'rank INT UNSIGNED' 'suggestion schema no longer uses a reserved SQL keyword'
Assert-Contains 'src/Service/MailService.php' 'renderProposalHtml' 'proposal mails render HTML buttons'
Assert-Contains 'src/Service/IcsService.php' 'calendar.google.com/calendar/render' 'confirmed appointments expose a Google Calendar template link'
Assert-Contains 'src/Admin/Menu.php' 'In Google Kalender' 'calendar view offers the Google Calendar export action'
Assert-Contains 'src/Service/MailService.php' 'sendTeamNotification' 'new requests notify configured team members'
Assert-Contains 'src/Service/MailService.php' 'sendResponse' 'team can send acceptance, rejection, and questions'
Assert-Contains 'src/Service/MailService.php' 'acceptUrl' 'proposal mails include public acceptance links'
Assert-Contains 'src/Service/MailService.php' 'Content-Type: text/html; charset=UTF-8' 'proposal mails are sent as HTML'
Assert-Contains 'src/Service/PublicSuggestionResponseService.php' 'admin_post_nopriv_pov_accept_suggestion' 'public proposal acceptance works without login'
Assert-Contains 'src/Service/PublicSuggestionResponseService.php' 'hash_hmac' 'public proposal acceptance links are signed'
Assert-Contains 'src/Service/PublicSuggestionResponseService.php' 'withRequestLock' 'public proposal acceptance is serialized per request'
Assert-Contains 'src/Repository/SuggestionRepository.php' 'AND state = %s' 'public proposal acceptance changes only a still-sent suggestion'
Assert-Contains 'src/Repository/SuggestionRepository.php' 'acceptPublicChoice' 'accepted public proposal expires alternatives'
Assert-Contains 'src/Plugin.php' 'PublicSuggestionResponseService' 'public proposal acceptance service is registered'
Assert-Contains 'src/Plugin.php' '(new FrontendAccess())->register();' 'plugin registers the optional booking access gate'
Assert-Contains 'src/Security/FrontendAccess.php' "public const PASSWORD = 'Ocean'" 'booking access uses the agreed presentation password'
Assert-Contains 'src/Security/FrontendAccess.php' 'hash_equals(self::PASSWORD, $password)' 'booking password is compared without timing leaks'
Assert-Contains 'src/Security/FrontendAccess.php' 'httponly' 'booking access cookie is unavailable to frontend JavaScript'
Assert-Contains 'src/Security/FrontendAccess.php' "'samesite' => 'Lax'" 'booking access cookie has an explicit same-site policy'
Assert-Contains 'src/Security/FrontendAccess.php' "define('DONOTCACHEPAGE', true)" 'password-protected booking pages opt out of page caching'
Assert-Contains 'src/Rest/PublicCalendarController.php' "[FrontendAccess::class, 'authorizeRest']" 'password gate protects public calendar data'
Assert-Contains 'src/Rest/RecommendationController.php' "[FrontendAccess::class, 'authorizeRest']" 'password gate protects route recommendations'
Assert-Contains 'src/Rest/RequestController.php' "[FrontendAccess::class, 'authorizeRest']" 'password gate protects request submission'
Assert-Contains 'src/Admin/Menu.php' 'name="pov_frontend_password_enabled"' 'backend exposes the booking password toggle'
Assert-Contains 'uninstall.php' "`$wpdb->esc_like('pov_')" 'full uninstall also removes non-autoloaded route snapshots'
Assert-Contains 'src/Service/IcsService.php' 'CONTACT:' 'ICS files include contact details'
Assert-Contains 'src/Service/IcsService.php' 'ORGANIZER;CN=' 'ICS files include organizer e-mail when present'
Assert-Contains 'src/Service/IcsService.php' 'Telefon: ' 'calendar exports include contact phone'
Assert-Contains 'src/Service/IcsService.php' 'E-Mail: ' 'calendar exports include contact e-mail'
Assert-Contains 'src/Routing/OsrmRoutingProvider.php' 'table/v1/driving' 'OSRM matrix endpoint is implemented'
Assert-Contains 'src/Routing/OsrmRoutingProvider.php' "'annotations' => 'distance,duration'" 'OSRM matrix requests distances and durations'
Assert-Contains 'src/Routing/OsrmRoutingProvider.php' 'coordinatePathPart' 'OSRM coordinates are formatted without encoded comma'
Assert-NotContains 'src/Routing/OsrmRoutingProvider.php' 'rawurlencode' 'OSRM coordinate path does not encode commas'
Assert-NotContains 'src/Routing/OsrmRoutingProvider.php' 'Matrix ist im MVP als austauschbarer Provider vorbereitet' 'matrix stub was removed'
Assert-NotContains 'templates/frontend-booking.php' 'besonders gut anbieten.</span>' 'frontend removes redundant recommendation descriptions'
Assert-Contains 'templates/frontend-booking.php' 'data-action="confirm-calendar-selection"' 'calendar selection requires explicit confirmation'
Assert-NotContains 'templates/frontend-booking.php' 'data-action="select-calendar-week"' 'calendar needs no separate week-selection control'
Assert-Contains 'assets/dist/frontend.js' 'function stageCalendarDate(date)' 'calendar first stages a day instead of opening the form'
Assert-Contains 'assets/dist/frontend.js' 'function confirmCalendarSelection()' 'calendar confirmation transfers the staged selection to the request'
Assert-Contains 'assets/vendor/pov-calendar/pov-calendar.js' 'setSelection(start, end)' 'calendar supports a visible date range'
Assert-Contains 'assets/dist/frontend.css' '.pov-day[data-selection="range"]' 'calendar range has visual selection feedback'
Assert-Contains 'assets/dist/frontend.css' 'background: #dce2e5' 'calendar selection uses one neutral grey fill'
Assert-Contains 'assets/dist/frontend.css' '.pov-day[data-weekend="true"][data-requestable="true"]' 'requestable weekends use the yellow calendar state'
Assert-Contains 'assets/vendor/pov-calendar/pov-calendar.js' "['tour', 'walk_in'].includes(row.public_state)" 'calendar keeps location and public-event hints'
Assert-Contains 'templates/frontend-booking.php' 'Einzeltermine oder Zeiträume anfragbar' 'calendar explains single-date and range requests concisely'
Assert-Contains 'src/Admin/Menu.php' "'pov_school_grade_options'" 'backend exposes configurable public school grades'
Assert-Contains 'templates/frontend-booking.php' "get_option('pov_school_grade_options', '3,4')" 'public grade choices use the backend configuration'
Assert-NotContains 'templates/frontend-booking.php' '>Wunschzeitraum anfragen<' 'calendar is the single date and range selection surface'
Assert-NotContains 'assets/dist/frontend.css' 'rgba(245, 219, 162, .45)' 'best route suggestion is no longer misleadingly yellow'
Assert-Contains 'src/Admin/Menu.php' 'seasonalStatePanel()' 'calendar shows where seasonal state availability is configured'
Assert-Contains 'src/Service/PublicRecommendationService.php' 'SeasonalStateService' 'public recommendations honor seasonal tour regions'
Assert-Contains 'src/Rest/RequestController.php' 'rangeHasAllowedDay' 'range requests honor seasonal tour regions'
Assert-Contains 'src/Admin/Menu.php' 'manual_visibility' 'manual calendar entries support internal and public tour stops'
Assert-Contains 'src/Database/Schema.php' 'request_id BIGINT UNSIGNED NULL' 'public calendar events can remain linked to their request hub'
Assert-Contains 'src/Admin/Menu.php' '$exportAppointments' 'linked public events are not exported twice'
Assert-True (Test-Path (Join-Path $root 'tests/run-seasonal-state.php')) 'executable seasonal-state regression test exists'

$visibleFiles = @(
    'templates/frontend-booking.php',
    'assets/dist/frontend.js',
    'src/Activation.php',
    'src/Admin/Menu.php',
    'src/Domain/RequestStatus.php',
    'src/Domain/WorkState.php',
    'src/Domain/CalendarState.php',
    'docs/acceptance-test.md',
    'docs/assumptions.md'
)

$badWords = @(
    'Tuebingen', 'Wuerttemberg', 'Thueringen', 'fuer ', 'Fuer ', 'pruef',
    'moeglich', 'waehle', 'Schueler', 'Rueckmeldung', 'Gruesse',
    'Bestaetigt', 'verfuegbar', 'Eingeschraenkt', 'oeffentlich',
    'Vorschlaege', 'Datenschutzerklaerung', 'Foerderschule', 'Strasse'
)

foreach ($file in $visibleFiles) {
    $text = Read-Text $file
    foreach ($word in $badWords) {
        Assert-True (-not $text.Contains($word)) "visible text in $file has no '$word'"
    }
}

Write-Host 'Static checks passed.'
